- name: create 7z download dir
  file:
    path: /root/7z
    state: directory
    mode: '0755'

- name: download 7z
  get_url:
    url: '{{ sevenzip_binary_url }}'
    dest: /root/7z/archive.tar.gz
    mode: '0700'

- name: unarchive 7z
  unarchive:
    src: /root/7z/archive.tar.gz
    remote_src: yes
    dest: /root/7z

- name: copy 7zz binary
  shell: |
    set -o pipefail
    cp /root/7z/7zz /usr/local/bin/
    chmod 755 /usr/local/bin/7zz
    chown root:root /usr/local/bin/7zz
  args:
    executable: /bin/bash
  changed_when: False

- name: db_dest_path as fact
  set_fact:
    db_dest_path: '{{ base_path }}/chains/{{ polkadot_network_id }}'
  when: base_path is defined

- name: db_dest_path as fact
  set_fact:
    db_dest_path: '/home/polkadot/.local/share/polkadot/chains/{{ polkadot_network_id }}'
  when: base_path is undefined  

- name: download db
  get_url:
    url: '{{ polkadot_db_snapshot_url }}'
    checksum: '{{ polkadot_db_snapshot_checksum | quote }}'
    dest: '{{ db_dest_path }}/db.new.7z'
    mode: '0700'
    owner: 'polkadot'
    group: 'polkadot'  

- name: stop polkadot service
  systemd:
    name: polkadot.service
    state: stopped

- name: unpack db
  shell: |
    set -o pipefail
    cd {{ db_dest_path }}
    mv db db.back
    7zz x db.new.7z
    rm db.new.7z
    chown -R polkadot:polkadot db/
  args:
    executable: /bin/bash

- name: start polkadot service
  systemd:
    name: polkadot.service
    state: started
